export interface User {
  id: string;
  email: string;
  role: "organization" | "performer";
  name: string;
  parentOrgId?: string;
  isManager?: boolean;
  password: string;
}

export interface Venue {
  id: string;
  organizationId: string;
  name: string;
  address: string;
  description: string;
  capacity: number;
  type: string;
  equipment: string[];
  policies: string[];
  imageUrl: string;
  managerIds?: string[];
}

export interface BookableSlot {
  id: string;
  venueId: string;
  date: string; // YYYY-MM-DD
  startTime: string; // HH:MM
  endTime: string; // HH:MM
  budget: number;
  status: "Available" | "Pending" | "Booked" | "Blocked";
  performerId: string | null;
}

export interface Performer {
  id: string;
  userId: string;
  name: string;
  biography: string;
  genres: string[];
  pricing: number;
  languages: string[];
  experience: string;
  travelRadius: number; // in miles/km
  equipmentNeeded: string[];
  imageUrl: string;
  completionPercentage: number;
}

export interface Booking {
  id: string;
  slotId: string;
  venueId: string;
  performerId: string;
  date: string;
  startTime: string;
  endTime: string;
  budget: number;
  status: "Pending" | "Confirmed" | "Rejected" | "Cancelled";
  createdAt: string;
}

export interface Message {
  id: string;
  senderId: string;
  receiverId: string;
  content: string;
  timestamp: string;
}

export interface Notification {
  id: string;
  userId: string;
  title: string;
  message: string;
  read: boolean;
  createdAt: string;
}

export interface Review {
  id: string;
  bookingId: string;
  reviewerId: string;
  revieweeId: string;
  rating: number;
  comment: string;
  createdAt: string;
}

export interface VoiceAssistant {
  id: string;
  organizationId: string;
  vapiAssistantId: string | null;
  name: string;
  industry: string;
  status: "pending" | "active" | "updating" | "failed";
  errorMessage: string | null;
  config: any;
  lastSyncedAt: string | null;
  createdAt: string;
}

export interface VoiceCallLog {
  id: string;
  assistantId: string;
  vapiCallId: string;
  type: string;
  startedAt: string;
  endedAt: string;
  duration: number;
  cost: number;
  status: string;
  transcript: string;
  summary: string;
  recordingUrl: string;
}

export const voiceAssistants: VoiceAssistant[] = [];
export const voiceCallLogs: VoiceCallLog[] = [];

// ── Users (9 accounts, unchanged) ────────────────────────────────────
export const users: User[] = [
  // Owners
  {
    id: "u-org-1",
    email: "org1@stagehub.com",
    password: "org1@stagehub",
    role: "organization",
    name: "ABC Hospitality Group",
  },
  {
    id: "u-org-2",
    email: "org2@stagehub.com",
    password: "org2@stagehub",
    role: "organization",
    name: "XYZ Entertainment Group",
  },

  // Owner 1 Managers (ABC)
  {
    id: "u-mgr-1",
    email: "john@stagehub.com",
    password: "mgr1@stagehub",
    role: "organization",
    name: "John (Sector 17 Café Manager)",
    parentOrgId: "u-org-1",
    isManager: true,
  },
  {
    id: "u-mgr-2",
    email: "alice@stagehub.com",
    password: "mgr2@stagehub",
    role: "organization",
    name: "Alice (Downtown Club Manager)",
    parentOrgId: "u-org-1",
    isManager: true,
  },

  // Owner 2 Managers (XYZ)
  {
    id: "u-mgr-3",
    email: "david@stagehub.com",
    password: "mgr3@stagehub",
    role: "organization",
    name: "David (Redwood Tavern Manager)",
    parentOrgId: "u-org-2",
    isManager: true,
  },
  {
    id: "u-mgr-4",
    email: "emma@stagehub.com",
    password: "mgr4@stagehub",
    role: "organization",
    name: "Emma (Skyline Rooftop Manager)",
    parentOrgId: "u-org-2",
    isManager: true,
  },

  // Performers
  {
    id: "u-perf-1",
    email: "perf1@stagehub.com",
    password: "perf1@stagehub",
    role: "performer",
    name: "Acoustic Duo (Sarah & Jack)",
  },
  {
    id: "u-perf-2",
    email: "perf2@stagehub.com",
    password: "perf2@stagehub",
    role: "performer",
    name: "DJ Electro",
  },
  {
    id: "u-perf-3",
    email: "perf3@stagehub.com",
    password: "perf3@stagehub",
    role: "performer",
    name: "Mike the Comedian",
  },
];

// ── Venues (5 venues, unchanged) ──────────────────────────────────────
export const venues: Venue[] = [
  // ABC Group Venues (Owner 1)
  {
    id: "v-1",
    organizationId: "u-org-1",
    name: "Sector 17 Brew & Cafe",
    address: "1024 Market St, Sector 17, Cityville",
    description:
      "A cozy indie cafe serving craft beer and artisanal coffees. Features a small wooden stage perfect for solo artists or duos.",
    capacity: 50,
    type: "Café",
    equipment: ["1x Acoustic Guitar Amp", "2x Vocal Mics", "Small PA System"],
    policies: [
      "No heavy metal",
      "Performers must arrive 30 mins early",
      "Sound limit 85dB",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&auto=format&fit=crop&q=80",
    managerIds: ["u-mgr-1"],
  },
  {
    id: "v-2",
    organizationId: "u-org-1",
    name: "The Downtown Club & Lounge",
    address: "405 Broadway Ave, Downtown",
    description:
      "A sleek, neon-lit lounge with high-end cocktail service and a large dancing floor. Designed for DJs and high-energy bands.",
    capacity: 200,
    type: "Club",
    equipment: [
      "Pioneer DJ Controller",
      "Full Sound System with Subwoofers",
      "Stage Lighting",
      "Wireless Mics",
    ],
    policies: [
      "DJs only (unless approved)",
      "18+ Crowd",
      "Set list must be shared beforehand",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&auto=format&fit=crop&q=80",
    managerIds: ["u-mgr-2"],
  },
  {
    id: "v-5",
    organizationId: "u-org-1",
    name: "Metropolitan Banquet Hall & Resort",
    address: "88 Grand Parkway, Resort District",
    description:
      "Our flagship event center. A massive luxury ballroom catering to corporate events, theater groups, and large-scale bands.",
    capacity: 600,
    type: "Resort",
    equipment: [
      "Full Grand Stage",
      "Line Array PA System",
      "Backstage Greenroom",
      "Smoke Machine",
      "Digital Mixing Board",
    ],
    policies: [
      "Soundcheck required 2 hours prior",
      "Strict 11 PM curfew",
      "Professional attire required",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&auto=format&fit=crop&q=80",
    managerIds: [],
  },

  // XYZ Group Venues (Owner 2)
  {
    id: "v-3",
    organizationId: "u-org-2",
    name: "Redwood Tavern & Grill",
    address: "908 Timberline Rd, Redwood Hills",
    description:
      "Rustic wooden mountain lodge serving burgers and local ciders. Attracts folk, rock, and blues performers for open mic weekends.",
    capacity: 120,
    type: "Restaurant",
    equipment: [
      "Fender Twin Reverb Amp",
      "Drum Kit (shells only)",
      "3x Vocal Mics",
    ],
    policies: [
      "Acoustic & Soft Rock only",
      "Tips allowed",
      "Must bring own cables",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80",
    managerIds: ["u-mgr-3"],
  },
  {
    id: "v-4",
    organizationId: "u-org-2",
    name: "Skyline Rooftop Bar",
    address: "888 Highrise Blvd, Penthouse Suite",
    description:
      "Elegant sky bar with 360 rooftop city views. Focuses on premium electronic, jazz fusion, and modern instrumental performance.",
    capacity: 80,
    type: "Club",
    equipment: [
      "Soundcraft 12-ch Mixer",
      "Premium JBL PA Speakers",
      "Keyboard Stand",
    ],
    policies: [
      "Smart casual attire",
      "No drum kits",
      "Setup must be completed by 5 PM",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1570560258879-af7f8e1447ac?w=800&auto=format&fit=crop&q=80",
    managerIds: ["u-mgr-4"],
  },
];

// ── Performers (3 performers, unchanged) ─────────────────────────────
export const performers: Performer[] = [
  {
    id: "p-1",
    userId: "u-perf-1",
    name: "Acoustic Duo (Sarah & Jack)",
    biography:
      "Sarah and Jack are an acoustic cover duo specializing in warm indie-folk adaptations of modern pop hits. Perfect for cafes, lounges, and corporate brunches.",
    genres: ["Folk", "Pop", "Acoustic"],
    pricing: 180,
    languages: ["English", "Spanish"],
    experience: "5+ years performing in hotel lounges and local cafes",
    travelRadius: 25,
    equipmentNeeded: [
      "2x Vocal Mics",
      "1x Acoustic Guitar DI box",
      "1x Keyboard DI box",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80",
    completionPercentage: 90,
  },
  {
    id: "p-2",
    userId: "u-perf-2",
    name: "DJ Electro",
    biography:
      "DJ Electro brings dynamic house, techno, and ambient deep-house sets to premier clubs and rooftops. Specializes in creating a high-end, immersive audio-visual experience.",
    genres: ["Electronic", "House", "Techno"],
    pricing: 450,
    languages: ["English", "German"],
    experience: "Resident DJ at Club Prism and guest performance in Ibiza",
    travelRadius: 50,
    equipmentNeeded: [
      "Pioneer DJ Controller",
      "Booth Monitors",
      "XLR outputs on stage",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1571266028243-3716f02d2d2e?w=800&auto=format&fit=crop&q=80",
    completionPercentage: 95,
  },
  {
    id: "p-3",
    userId: "u-perf-3",
    name: "Mike the Comedian",
    biography:
      "A clean stand-up comedian focusing on observational humor, corporate culture, and family stories. 100% clean comedy, highly interactive.",
    genres: ["Comedy", "Corporate"],
    pricing: 300,
    languages: ["English"],
    experience:
      "Performances at the Comedy Cellar and corporate holiday parties",
    travelRadius: 15,
    equipmentNeeded: ["Wireless Vocal Mic", "Mic Stand", "Bar stool"],
    imageUrl:
      "https://images.unsplash.com/photo-1585699324551-f6c309eed262?w=800&auto=format&fit=crop&q=80",
    completionPercentage: 80,
  },
];

// ── Date helpers ──────────────────────────────────────────────────────
const today = new Date();
const formatDate = (daysOffset: number) => {
  const d = new Date(today);
  d.setDate(today.getDate() + daysOffset);
  return d.toISOString().split("T")[0];
};

// ── Bookable Slots ─────────────────────
export const bookableSlots: BookableSlot[] = [
  {
    id: "s-1000",
    venueId: "v-1",
    date: formatDate(-15),
    startTime: "17:00",
    endTime: "19:00",
    budget: 185,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1001",
    venueId: "v-1",
    date: formatDate(-14),
    startTime: "17:00",
    endTime: "19:00",
    budget: 284,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1002",
    venueId: "v-1",
    date: formatDate(-14),
    startTime: "19:00",
    endTime: "21:00",
    budget: 285,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1003",
    venueId: "v-1",
    date: formatDate(-12),
    startTime: "17:00",
    endTime: "19:00",
    budget: 136,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1004",
    venueId: "v-1",
    date: formatDate(-12),
    startTime: "19:00",
    endTime: "21:00",
    budget: 166,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1005",
    venueId: "v-1",
    date: formatDate(-11),
    startTime: "17:00",
    endTime: "19:00",
    budget: 126,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1006",
    venueId: "v-1",
    date: formatDate(-11),
    startTime: "19:00",
    endTime: "21:00",
    budget: 138,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1007",
    venueId: "v-1",
    date: formatDate(-10),
    startTime: "17:00",
    endTime: "19:00",
    budget: 196,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1008",
    venueId: "v-1",
    date: formatDate(-9),
    startTime: "17:00",
    endTime: "19:00",
    budget: 163,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1009",
    venueId: "v-1",
    date: formatDate(-9),
    startTime: "19:00",
    endTime: "21:00",
    budget: 248,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1010",
    venueId: "v-1",
    date: formatDate(-9),
    startTime: "21:00",
    endTime: "23:00",
    budget: 147,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1011",
    venueId: "v-1",
    date: formatDate(-6),
    startTime: "17:00",
    endTime: "19:00",
    budget: 206,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1012",
    venueId: "v-1",
    date: formatDate(-6),
    startTime: "19:00",
    endTime: "21:00",
    budget: 139,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1013",
    venueId: "v-1",
    date: formatDate(-6),
    startTime: "21:00",
    endTime: "23:00",
    budget: 293,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1014",
    venueId: "v-1",
    date: formatDate(-4),
    startTime: "17:00",
    endTime: "19:00",
    budget: 214,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1015",
    venueId: "v-1",
    date: formatDate(-4),
    startTime: "19:00",
    endTime: "21:00",
    budget: 136,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1016",
    venueId: "v-1",
    date: formatDate(-3),
    startTime: "17:00",
    endTime: "19:00",
    budget: 161,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1017",
    venueId: "v-1",
    date: formatDate(-2),
    startTime: "17:00",
    endTime: "19:00",
    budget: 291,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1018",
    venueId: "v-1",
    date: formatDate(-2),
    startTime: "19:00",
    endTime: "21:00",
    budget: 212,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1019",
    venueId: "v-1",
    date: formatDate(-1),
    startTime: "17:00",
    endTime: "19:00",
    budget: 119,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1020",
    venueId: "v-1",
    date: formatDate(-1),
    startTime: "19:00",
    endTime: "21:00",
    budget: 277,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1021",
    venueId: "v-1",
    date: formatDate(1),
    startTime: "17:00",
    endTime: "19:00",
    budget: 286,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1022",
    venueId: "v-1",
    date: formatDate(1),
    startTime: "19:00",
    endTime: "21:00",
    budget: 189,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1023",
    venueId: "v-1",
    date: formatDate(1),
    startTime: "21:00",
    endTime: "23:00",
    budget: 180,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1024",
    venueId: "v-1",
    date: formatDate(4),
    startTime: "17:00",
    endTime: "19:00",
    budget: 152,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1025",
    venueId: "v-1",
    date: formatDate(4),
    startTime: "19:00",
    endTime: "21:00",
    budget: 164,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1026",
    venueId: "v-1",
    date: formatDate(6),
    startTime: "17:00",
    endTime: "19:00",
    budget: 201,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1027",
    venueId: "v-1",
    date: formatDate(6),
    startTime: "19:00",
    endTime: "21:00",
    budget: 298,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1028",
    venueId: "v-1",
    date: formatDate(8),
    startTime: "17:00",
    endTime: "19:00",
    budget: 111,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1029",
    venueId: "v-1",
    date: formatDate(9),
    startTime: "17:00",
    endTime: "19:00",
    budget: 280,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1030",
    venueId: "v-1",
    date: formatDate(9),
    startTime: "19:00",
    endTime: "21:00",
    budget: 236,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1031",
    venueId: "v-1",
    date: formatDate(10),
    startTime: "17:00",
    endTime: "19:00",
    budget: 296,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1032",
    venueId: "v-1",
    date: formatDate(10),
    startTime: "19:00",
    endTime: "21:00",
    budget: 263,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1033",
    venueId: "v-1",
    date: formatDate(11),
    startTime: "17:00",
    endTime: "19:00",
    budget: 281,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1034",
    venueId: "v-1",
    date: formatDate(11),
    startTime: "19:00",
    endTime: "21:00",
    budget: 265,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1035",
    venueId: "v-1",
    date: formatDate(11),
    startTime: "21:00",
    endTime: "23:00",
    budget: 140,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1036",
    venueId: "v-1",
    date: formatDate(12),
    startTime: "17:00",
    endTime: "19:00",
    budget: 287,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1037",
    venueId: "v-1",
    date: formatDate(13),
    startTime: "17:00",
    endTime: "19:00",
    budget: 127,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1038",
    venueId: "v-1",
    date: formatDate(13),
    startTime: "19:00",
    endTime: "21:00",
    budget: 242,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1039",
    venueId: "v-1",
    date: formatDate(14),
    startTime: "17:00",
    endTime: "19:00",
    budget: 258,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1040",
    venueId: "v-1",
    date: formatDate(14),
    startTime: "19:00",
    endTime: "21:00",
    budget: 188,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1041",
    venueId: "v-1",
    date: formatDate(14),
    startTime: "21:00",
    endTime: "23:00",
    budget: 143,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1042",
    venueId: "v-1",
    date: formatDate(15),
    startTime: "17:00",
    endTime: "19:00",
    budget: 135,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1043",
    venueId: "v-2",
    date: formatDate(-15),
    startTime: "17:00",
    endTime: "19:00",
    budget: 251,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1044",
    venueId: "v-2",
    date: formatDate(-14),
    startTime: "17:00",
    endTime: "19:00",
    budget: 153,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1045",
    venueId: "v-2",
    date: formatDate(-13),
    startTime: "17:00",
    endTime: "19:00",
    budget: 110,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1046",
    venueId: "v-2",
    date: formatDate(-13),
    startTime: "19:00",
    endTime: "21:00",
    budget: 285,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1047",
    venueId: "v-2",
    date: formatDate(-12),
    startTime: "17:00",
    endTime: "19:00",
    budget: 249,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1048",
    venueId: "v-2",
    date: formatDate(-12),
    startTime: "19:00",
    endTime: "21:00",
    budget: 113,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1049",
    venueId: "v-2",
    date: formatDate(-11),
    startTime: "17:00",
    endTime: "19:00",
    budget: 291,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1050",
    venueId: "v-2",
    date: formatDate(-11),
    startTime: "19:00",
    endTime: "21:00",
    budget: 183,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1051",
    venueId: "v-2",
    date: formatDate(-8),
    startTime: "17:00",
    endTime: "19:00",
    budget: 294,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1052",
    venueId: "v-2",
    date: formatDate(-7),
    startTime: "17:00",
    endTime: "19:00",
    budget: 150,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1053",
    venueId: "v-2",
    date: formatDate(-3),
    startTime: "17:00",
    endTime: "19:00",
    budget: 177,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1054",
    venueId: "v-2",
    date: formatDate(-2),
    startTime: "17:00",
    endTime: "19:00",
    budget: 264,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1055",
    venueId: "v-2",
    date: formatDate(-1),
    startTime: "17:00",
    endTime: "19:00",
    budget: 137,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1056",
    venueId: "v-2",
    date: formatDate(-1),
    startTime: "19:00",
    endTime: "21:00",
    budget: 200,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1057",
    venueId: "v-2",
    date: formatDate(-1),
    startTime: "21:00",
    endTime: "23:00",
    budget: 148,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1058",
    venueId: "v-2",
    date: formatDate(1),
    startTime: "17:00",
    endTime: "19:00",
    budget: 174,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1059",
    venueId: "v-2",
    date: formatDate(1),
    startTime: "19:00",
    endTime: "21:00",
    budget: 184,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1060",
    venueId: "v-2",
    date: formatDate(1),
    startTime: "21:00",
    endTime: "23:00",
    budget: 279,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1061",
    venueId: "v-2",
    date: formatDate(2),
    startTime: "17:00",
    endTime: "19:00",
    budget: 198,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1062",
    venueId: "v-2",
    date: formatDate(2),
    startTime: "19:00",
    endTime: "21:00",
    budget: 121,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1063",
    venueId: "v-2",
    date: formatDate(3),
    startTime: "17:00",
    endTime: "19:00",
    budget: 186,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1064",
    venueId: "v-2",
    date: formatDate(4),
    startTime: "17:00",
    endTime: "19:00",
    budget: 263,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1065",
    venueId: "v-2",
    date: formatDate(4),
    startTime: "19:00",
    endTime: "21:00",
    budget: 255,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1066",
    venueId: "v-2",
    date: formatDate(4),
    startTime: "21:00",
    endTime: "23:00",
    budget: 107,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1067",
    venueId: "v-2",
    date: formatDate(5),
    startTime: "17:00",
    endTime: "19:00",
    budget: 233,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1068",
    venueId: "v-2",
    date: formatDate(5),
    startTime: "19:00",
    endTime: "21:00",
    budget: 221,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1069",
    venueId: "v-2",
    date: formatDate(6),
    startTime: "17:00",
    endTime: "19:00",
    budget: 262,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1070",
    venueId: "v-2",
    date: formatDate(6),
    startTime: "19:00",
    endTime: "21:00",
    budget: 297,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1071",
    venueId: "v-2",
    date: formatDate(6),
    startTime: "21:00",
    endTime: "23:00",
    budget: 239,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1072",
    venueId: "v-2",
    date: formatDate(7),
    startTime: "17:00",
    endTime: "19:00",
    budget: 256,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1073",
    venueId: "v-2",
    date: formatDate(7),
    startTime: "19:00",
    endTime: "21:00",
    budget: 205,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1074",
    venueId: "v-2",
    date: formatDate(9),
    startTime: "17:00",
    endTime: "19:00",
    budget: 227,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1075",
    venueId: "v-2",
    date: formatDate(9),
    startTime: "19:00",
    endTime: "21:00",
    budget: 254,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1076",
    venueId: "v-2",
    date: formatDate(11),
    startTime: "17:00",
    endTime: "19:00",
    budget: 250,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1077",
    venueId: "v-2",
    date: formatDate(11),
    startTime: "19:00",
    endTime: "21:00",
    budget: 166,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1078",
    venueId: "v-2",
    date: formatDate(11),
    startTime: "21:00",
    endTime: "23:00",
    budget: 292,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1079",
    venueId: "v-2",
    date: formatDate(12),
    startTime: "17:00",
    endTime: "19:00",
    budget: 156,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1080",
    venueId: "v-2",
    date: formatDate(12),
    startTime: "19:00",
    endTime: "21:00",
    budget: 211,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1081",
    venueId: "v-2",
    date: formatDate(14),
    startTime: "17:00",
    endTime: "19:00",
    budget: 117,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1082",
    venueId: "v-2",
    date: formatDate(14),
    startTime: "19:00",
    endTime: "21:00",
    budget: 289,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1083",
    venueId: "v-2",
    date: formatDate(15),
    startTime: "17:00",
    endTime: "19:00",
    budget: 110,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1084",
    venueId: "v-2",
    date: formatDate(15),
    startTime: "19:00",
    endTime: "21:00",
    budget: 289,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1085",
    venueId: "v-2",
    date: formatDate(15),
    startTime: "21:00",
    endTime: "23:00",
    budget: 165,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1086",
    venueId: "v-5",
    date: formatDate(-14),
    startTime: "17:00",
    endTime: "19:00",
    budget: 260,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1087",
    venueId: "v-5",
    date: formatDate(-14),
    startTime: "19:00",
    endTime: "21:00",
    budget: 219,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1088",
    venueId: "v-5",
    date: formatDate(-14),
    startTime: "21:00",
    endTime: "23:00",
    budget: 193,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1089",
    venueId: "v-5",
    date: formatDate(-13),
    startTime: "17:00",
    endTime: "19:00",
    budget: 289,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1090",
    venueId: "v-5",
    date: formatDate(-12),
    startTime: "17:00",
    endTime: "19:00",
    budget: 220,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1091",
    venueId: "v-5",
    date: formatDate(-12),
    startTime: "19:00",
    endTime: "21:00",
    budget: 296,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1092",
    venueId: "v-5",
    date: formatDate(-12),
    startTime: "21:00",
    endTime: "23:00",
    budget: 139,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1093",
    venueId: "v-5",
    date: formatDate(-11),
    startTime: "17:00",
    endTime: "19:00",
    budget: 167,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1094",
    venueId: "v-5",
    date: formatDate(-11),
    startTime: "19:00",
    endTime: "21:00",
    budget: 219,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1095",
    venueId: "v-5",
    date: formatDate(-11),
    startTime: "21:00",
    endTime: "23:00",
    budget: 225,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1096",
    venueId: "v-5",
    date: formatDate(-9),
    startTime: "17:00",
    endTime: "19:00",
    budget: 141,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1097",
    venueId: "v-5",
    date: formatDate(-7),
    startTime: "17:00",
    endTime: "19:00",
    budget: 107,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1098",
    venueId: "v-5",
    date: formatDate(-7),
    startTime: "19:00",
    endTime: "21:00",
    budget: 118,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1099",
    venueId: "v-5",
    date: formatDate(-6),
    startTime: "17:00",
    endTime: "19:00",
    budget: 140,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1100",
    venueId: "v-5",
    date: formatDate(-6),
    startTime: "19:00",
    endTime: "21:00",
    budget: 181,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1101",
    venueId: "v-5",
    date: formatDate(-6),
    startTime: "21:00",
    endTime: "23:00",
    budget: 280,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1102",
    venueId: "v-5",
    date: formatDate(-5),
    startTime: "17:00",
    endTime: "19:00",
    budget: 145,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1103",
    venueId: "v-5",
    date: formatDate(-5),
    startTime: "19:00",
    endTime: "21:00",
    budget: 208,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1104",
    venueId: "v-5",
    date: formatDate(-4),
    startTime: "17:00",
    endTime: "19:00",
    budget: 219,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1105",
    venueId: "v-5",
    date: formatDate(-4),
    startTime: "19:00",
    endTime: "21:00",
    budget: 181,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1106",
    venueId: "v-5",
    date: formatDate(-2),
    startTime: "17:00",
    endTime: "19:00",
    budget: 262,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1107",
    venueId: "v-5",
    date: formatDate(-1),
    startTime: "17:00",
    endTime: "19:00",
    budget: 254,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1108",
    venueId: "v-5",
    date: formatDate(0),
    startTime: "17:00",
    endTime: "19:00",
    budget: 182,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1109",
    venueId: "v-5",
    date: formatDate(0),
    startTime: "19:00",
    endTime: "21:00",
    budget: 169,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1110",
    venueId: "v-5",
    date: formatDate(4),
    startTime: "17:00",
    endTime: "19:00",
    budget: 187,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1111",
    venueId: "v-5",
    date: formatDate(4),
    startTime: "19:00",
    endTime: "21:00",
    budget: 207,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1112",
    venueId: "v-5",
    date: formatDate(5),
    startTime: "17:00",
    endTime: "19:00",
    budget: 100,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1113",
    venueId: "v-5",
    date: formatDate(6),
    startTime: "17:00",
    endTime: "19:00",
    budget: 209,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1114",
    venueId: "v-5",
    date: formatDate(7),
    startTime: "17:00",
    endTime: "19:00",
    budget: 229,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1115",
    venueId: "v-5",
    date: formatDate(8),
    startTime: "17:00",
    endTime: "19:00",
    budget: 199,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1116",
    venueId: "v-5",
    date: formatDate(8),
    startTime: "19:00",
    endTime: "21:00",
    budget: 178,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1117",
    venueId: "v-5",
    date: formatDate(8),
    startTime: "21:00",
    endTime: "23:00",
    budget: 130,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1118",
    venueId: "v-5",
    date: formatDate(10),
    startTime: "17:00",
    endTime: "19:00",
    budget: 213,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1119",
    venueId: "v-5",
    date: formatDate(10),
    startTime: "19:00",
    endTime: "21:00",
    budget: 147,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1120",
    venueId: "v-5",
    date: formatDate(11),
    startTime: "17:00",
    endTime: "19:00",
    budget: 177,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1121",
    venueId: "v-5",
    date: formatDate(11),
    startTime: "19:00",
    endTime: "21:00",
    budget: 139,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1122",
    venueId: "v-5",
    date: formatDate(12),
    startTime: "17:00",
    endTime: "19:00",
    budget: 256,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1123",
    venueId: "v-5",
    date: formatDate(12),
    startTime: "19:00",
    endTime: "21:00",
    budget: 274,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1124",
    venueId: "v-5",
    date: formatDate(14),
    startTime: "17:00",
    endTime: "19:00",
    budget: 173,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1125",
    venueId: "v-5",
    date: formatDate(15),
    startTime: "17:00",
    endTime: "19:00",
    budget: 168,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1126",
    venueId: "v-5",
    date: formatDate(15),
    startTime: "19:00",
    endTime: "21:00",
    budget: 176,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1127",
    venueId: "v-5",
    date: formatDate(15),
    startTime: "21:00",
    endTime: "23:00",
    budget: 190,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1128",
    venueId: "v-3",
    date: formatDate(-15),
    startTime: "17:00",
    endTime: "19:00",
    budget: 187,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1129",
    venueId: "v-3",
    date: formatDate(-13),
    startTime: "17:00",
    endTime: "19:00",
    budget: 147,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1130",
    venueId: "v-3",
    date: formatDate(-12),
    startTime: "17:00",
    endTime: "19:00",
    budget: 267,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1131",
    venueId: "v-3",
    date: formatDate(-12),
    startTime: "19:00",
    endTime: "21:00",
    budget: 196,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1132",
    venueId: "v-3",
    date: formatDate(-11),
    startTime: "17:00",
    endTime: "19:00",
    budget: 141,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1133",
    venueId: "v-3",
    date: formatDate(-9),
    startTime: "17:00",
    endTime: "19:00",
    budget: 292,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1134",
    venueId: "v-3",
    date: formatDate(-9),
    startTime: "19:00",
    endTime: "21:00",
    budget: 297,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1135",
    venueId: "v-3",
    date: formatDate(-9),
    startTime: "21:00",
    endTime: "23:00",
    budget: 235,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1136",
    venueId: "v-3",
    date: formatDate(-8),
    startTime: "17:00",
    endTime: "19:00",
    budget: 156,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1137",
    venueId: "v-3",
    date: formatDate(-8),
    startTime: "19:00",
    endTime: "21:00",
    budget: 285,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1138",
    venueId: "v-3",
    date: formatDate(-8),
    startTime: "21:00",
    endTime: "23:00",
    budget: 126,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1139",
    venueId: "v-3",
    date: formatDate(-7),
    startTime: "17:00",
    endTime: "19:00",
    budget: 125,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1140",
    venueId: "v-3",
    date: formatDate(-7),
    startTime: "19:00",
    endTime: "21:00",
    budget: 100,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1141",
    venueId: "v-3",
    date: formatDate(-6),
    startTime: "17:00",
    endTime: "19:00",
    budget: 219,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1142",
    venueId: "v-3",
    date: formatDate(-6),
    startTime: "19:00",
    endTime: "21:00",
    budget: 115,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1143",
    venueId: "v-3",
    date: formatDate(-5),
    startTime: "17:00",
    endTime: "19:00",
    budget: 108,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1144",
    venueId: "v-3",
    date: formatDate(-5),
    startTime: "19:00",
    endTime: "21:00",
    budget: 253,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1145",
    venueId: "v-3",
    date: formatDate(-4),
    startTime: "17:00",
    endTime: "19:00",
    budget: 172,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1146",
    venueId: "v-3",
    date: formatDate(-4),
    startTime: "19:00",
    endTime: "21:00",
    budget: 233,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1147",
    venueId: "v-3",
    date: formatDate(-3),
    startTime: "17:00",
    endTime: "19:00",
    budget: 120,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1148",
    venueId: "v-3",
    date: formatDate(-3),
    startTime: "19:00",
    endTime: "21:00",
    budget: 173,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1149",
    venueId: "v-3",
    date: formatDate(-2),
    startTime: "17:00",
    endTime: "19:00",
    budget: 194,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1150",
    venueId: "v-3",
    date: formatDate(-1),
    startTime: "17:00",
    endTime: "19:00",
    budget: 145,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1151",
    venueId: "v-3",
    date: formatDate(-1),
    startTime: "19:00",
    endTime: "21:00",
    budget: 154,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1152",
    venueId: "v-3",
    date: formatDate(-1),
    startTime: "21:00",
    endTime: "23:00",
    budget: 178,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1153",
    venueId: "v-3",
    date: formatDate(1),
    startTime: "17:00",
    endTime: "19:00",
    budget: 263,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1154",
    venueId: "v-3",
    date: formatDate(1),
    startTime: "19:00",
    endTime: "21:00",
    budget: 110,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1155",
    venueId: "v-3",
    date: formatDate(1),
    startTime: "21:00",
    endTime: "23:00",
    budget: 280,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1156",
    venueId: "v-3",
    date: formatDate(3),
    startTime: "17:00",
    endTime: "19:00",
    budget: 256,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1157",
    venueId: "v-3",
    date: formatDate(3),
    startTime: "19:00",
    endTime: "21:00",
    budget: 100,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1158",
    venueId: "v-3",
    date: formatDate(4),
    startTime: "17:00",
    endTime: "19:00",
    budget: 245,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1159",
    venueId: "v-3",
    date: formatDate(4),
    startTime: "19:00",
    endTime: "21:00",
    budget: 128,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1160",
    venueId: "v-3",
    date: formatDate(4),
    startTime: "21:00",
    endTime: "23:00",
    budget: 192,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1161",
    venueId: "v-3",
    date: formatDate(6),
    startTime: "17:00",
    endTime: "19:00",
    budget: 223,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1162",
    venueId: "v-3",
    date: formatDate(6),
    startTime: "19:00",
    endTime: "21:00",
    budget: 239,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1163",
    venueId: "v-3",
    date: formatDate(6),
    startTime: "21:00",
    endTime: "23:00",
    budget: 145,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1164",
    venueId: "v-3",
    date: formatDate(9),
    startTime: "17:00",
    endTime: "19:00",
    budget: 170,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1165",
    venueId: "v-3",
    date: formatDate(9),
    startTime: "19:00",
    endTime: "21:00",
    budget: 238,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1166",
    venueId: "v-3",
    date: formatDate(11),
    startTime: "17:00",
    endTime: "19:00",
    budget: 131,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1167",
    venueId: "v-3",
    date: formatDate(12),
    startTime: "17:00",
    endTime: "19:00",
    budget: 295,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1168",
    venueId: "v-3",
    date: formatDate(14),
    startTime: "17:00",
    endTime: "19:00",
    budget: 153,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1169",
    venueId: "v-4",
    date: formatDate(-15),
    startTime: "17:00",
    endTime: "19:00",
    budget: 279,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1170",
    venueId: "v-4",
    date: formatDate(-15),
    startTime: "19:00",
    endTime: "21:00",
    budget: 280,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1171",
    venueId: "v-4",
    date: formatDate(-14),
    startTime: "17:00",
    endTime: "19:00",
    budget: 237,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1172",
    venueId: "v-4",
    date: formatDate(-11),
    startTime: "17:00",
    endTime: "19:00",
    budget: 224,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1173",
    venueId: "v-4",
    date: formatDate(-8),
    startTime: "17:00",
    endTime: "19:00",
    budget: 138,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1174",
    venueId: "v-4",
    date: formatDate(-6),
    startTime: "17:00",
    endTime: "19:00",
    budget: 133,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1175",
    venueId: "v-4",
    date: formatDate(-6),
    startTime: "19:00",
    endTime: "21:00",
    budget: 201,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1176",
    venueId: "v-4",
    date: formatDate(-6),
    startTime: "21:00",
    endTime: "23:00",
    budget: 214,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1177",
    venueId: "v-4",
    date: formatDate(-4),
    startTime: "17:00",
    endTime: "19:00",
    budget: 246,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1178",
    venueId: "v-4",
    date: formatDate(-4),
    startTime: "19:00",
    endTime: "21:00",
    budget: 106,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1179",
    venueId: "v-4",
    date: formatDate(-3),
    startTime: "17:00",
    endTime: "19:00",
    budget: 133,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1180",
    venueId: "v-4",
    date: formatDate(-2),
    startTime: "17:00",
    endTime: "19:00",
    budget: 265,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1181",
    venueId: "v-4",
    date: formatDate(-1),
    startTime: "17:00",
    endTime: "19:00",
    budget: 136,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1182",
    venueId: "v-4",
    date: formatDate(-1),
    startTime: "19:00",
    endTime: "21:00",
    budget: 165,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1183",
    venueId: "v-4",
    date: formatDate(0),
    startTime: "17:00",
    endTime: "19:00",
    budget: 211,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1184",
    venueId: "v-4",
    date: formatDate(0),
    startTime: "19:00",
    endTime: "21:00",
    budget: 276,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1185",
    venueId: "v-4",
    date: formatDate(0),
    startTime: "21:00",
    endTime: "23:00",
    budget: 193,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1186",
    venueId: "v-4",
    date: formatDate(2),
    startTime: "17:00",
    endTime: "19:00",
    budget: 292,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1187",
    venueId: "v-4",
    date: formatDate(2),
    startTime: "19:00",
    endTime: "21:00",
    budget: 161,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1188",
    venueId: "v-4",
    date: formatDate(3),
    startTime: "17:00",
    endTime: "19:00",
    budget: 267,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1189",
    venueId: "v-4",
    date: formatDate(3),
    startTime: "19:00",
    endTime: "21:00",
    budget: 190,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1190",
    venueId: "v-4",
    date: formatDate(4),
    startTime: "17:00",
    endTime: "19:00",
    budget: 234,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1191",
    venueId: "v-4",
    date: formatDate(4),
    startTime: "19:00",
    endTime: "21:00",
    budget: 278,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1192",
    venueId: "v-4",
    date: formatDate(5),
    startTime: "17:00",
    endTime: "19:00",
    budget: 206,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1193",
    venueId: "v-4",
    date: formatDate(5),
    startTime: "19:00",
    endTime: "21:00",
    budget: 255,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1194",
    venueId: "v-4",
    date: formatDate(6),
    startTime: "17:00",
    endTime: "19:00",
    budget: 190,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1195",
    venueId: "v-4",
    date: formatDate(6),
    startTime: "19:00",
    endTime: "21:00",
    budget: 256,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1196",
    venueId: "v-4",
    date: formatDate(6),
    startTime: "21:00",
    endTime: "23:00",
    budget: 210,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1197",
    venueId: "v-4",
    date: formatDate(7),
    startTime: "17:00",
    endTime: "19:00",
    budget: 298,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1198",
    venueId: "v-4",
    date: formatDate(9),
    startTime: "17:00",
    endTime: "19:00",
    budget: 132,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1199",
    venueId: "v-4",
    date: formatDate(9),
    startTime: "19:00",
    endTime: "21:00",
    budget: 167,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1200",
    venueId: "v-4",
    date: formatDate(9),
    startTime: "21:00",
    endTime: "23:00",
    budget: 126,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1201",
    venueId: "v-4",
    date: formatDate(10),
    startTime: "17:00",
    endTime: "19:00",
    budget: 280,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1202",
    venueId: "v-4",
    date: formatDate(10),
    startTime: "19:00",
    endTime: "21:00",
    budget: 179,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1203",
    venueId: "v-4",
    date: formatDate(10),
    startTime: "21:00",
    endTime: "23:00",
    budget: 106,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1204",
    venueId: "v-4",
    date: formatDate(11),
    startTime: "17:00",
    endTime: "19:00",
    budget: 259,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1205",
    venueId: "v-4",
    date: formatDate(11),
    startTime: "19:00",
    endTime: "21:00",
    budget: 188,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1206",
    venueId: "v-4",
    date: formatDate(11),
    startTime: "21:00",
    endTime: "23:00",
    budget: 175,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1207",
    venueId: "v-4",
    date: formatDate(12),
    startTime: "17:00",
    endTime: "19:00",
    budget: 105,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1208",
    venueId: "v-4",
    date: formatDate(13),
    startTime: "17:00",
    endTime: "19:00",
    budget: 138,
    status: "Blocked",
    performerId: null,
  },
  {
    id: "s-1209",
    venueId: "v-4",
    date: formatDate(13),
    startTime: "19:00",
    endTime: "21:00",
    budget: 141,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1210",
    venueId: "v-4",
    date: formatDate(14),
    startTime: "17:00",
    endTime: "19:00",
    budget: 189,
    status: "Pending",
    performerId: "p-1",
  },
  {
    id: "s-1211",
    venueId: "v-4",
    date: formatDate(14),
    startTime: "19:00",
    endTime: "21:00",
    budget: 280,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1212",
    venueId: "v-4",
    date: formatDate(14),
    startTime: "21:00",
    endTime: "23:00",
    budget: 157,
    status: "Booked",
    performerId: "p-1",
  },
  {
    id: "s-1213",
    venueId: "v-4",
    date: formatDate(15),
    startTime: "17:00",
    endTime: "19:00",
    budget: 130,
    status: "Available",
    performerId: null,
  },
  {
    id: "s-1214",
    venueId: "v-4",
    date: formatDate(15),
    startTime: "19:00",
    endTime: "21:00",
    budget: 181,
    status: "Booked",
    performerId: "p-1",
  },
];

// ── Bookings — 23 entries covering all statuses ────────────────────────
export const bookings: Booking[] = [
  // ABC upcoming
  {
    id: "b-1",
    slotId: "s-5",
    venueId: "v-2",
    performerId: "p-2",
    date: formatDate(6),
    startTime: "21:00",
    endTime: "00:00",
    budget: 450,
    status: "Confirmed",
    createdAt: new Date().toISOString(),
  },
  {
    id: "b-4",
    slotId: "s-3",
    venueId: "v-1",
    performerId: "p-1",
    date: formatDate(5),
    startTime: "19:00",
    endTime: "22:00",
    budget: 180,
    status: "Pending",
    createdAt: new Date().toISOString(),
  },
  {
    id: "b-6",
    slotId: "s-15",
    venueId: "v-1",
    performerId: "p-3",
    date: formatDate(14),
    startTime: "17:00",
    endTime: "20:00",
    budget: 175,
    status: "Confirmed",
    createdAt: new Date(
      today.getTime() - 1 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },
  {
    id: "b-7",
    slotId: "s-16",
    venueId: "v-1",
    performerId: "p-2",
    date: formatDate(16),
    startTime: "20:00",
    endTime: "23:00",
    budget: 190,
    status: "Pending",
    createdAt: new Date().toISOString(),
  },
  {
    id: "b-8",
    slotId: "s-19",
    venueId: "v-2",
    performerId: "p-2",
    date: formatDate(12),
    startTime: "21:00",
    endTime: "01:00",
    budget: 480,
    status: "Confirmed",
    createdAt: new Date(
      today.getTime() - 2 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },
  {
    id: "b-9",
    slotId: "s-20",
    venueId: "v-2",
    performerId: "p-2",
    date: formatDate(15),
    startTime: "22:00",
    endTime: "01:00",
    budget: 520,
    status: "Pending",
    createdAt: new Date().toISOString(),
  },
  {
    id: "b-10",
    slotId: "s-23",
    venueId: "v-5",
    performerId: "p-1",
    date: formatDate(14),
    startTime: "17:00",
    endTime: "22:00",
    budget: 1200,
    status: "Confirmed",
    createdAt: new Date(
      today.getTime() - 3 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },
  {
    id: "b-11",
    slotId: "s-25",
    venueId: "v-5",
    performerId: "p-3",
    date: formatDate(28),
    startTime: "19:00",
    endTime: "22:00",
    budget: 1100,
    status: "Pending",
    createdAt: new Date().toISOString(),
  },

  // XYZ upcoming
  {
    id: "b-2",
    slotId: "s-10",
    venueId: "v-3",
    performerId: "p-1",
    date: formatDate(5),
    startTime: "19:00",
    endTime: "22:00",
    budget: 300,
    status: "Confirmed",
    createdAt: new Date().toISOString(),
  },
  {
    id: "b-3",
    slotId: "s-12",
    venueId: "v-4",
    performerId: "p-2",
    date: formatDate(7),
    startTime: "18:00",
    endTime: "21:00",
    budget: 450,
    status: "Confirmed",
    createdAt: new Date().toISOString(),
  },
  {
    id: "b-5",
    slotId: "s-9",
    venueId: "v-3",
    performerId: "p-3",
    date: formatDate(3),
    startTime: "18:00",
    endTime: "21:00",
    budget: 320,
    status: "Pending",
    createdAt: new Date().toISOString(),
  },
  {
    id: "b-12",
    slotId: "s-27",
    venueId: "v-3",
    performerId: "p-2",
    date: formatDate(10),
    startTime: "18:30",
    endTime: "21:30",
    budget: 310,
    status: "Confirmed",
    createdAt: new Date(
      today.getTime() - 1 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },
  {
    id: "b-13",
    slotId: "s-29",
    venueId: "v-3",
    performerId: "p-1",
    date: formatDate(17),
    startTime: "19:00",
    endTime: "22:00",
    budget: 350,
    status: "Pending",
    createdAt: new Date().toISOString(),
  },
  {
    id: "b-14",
    slotId: "s-31",
    venueId: "v-4",
    performerId: "p-1",
    date: formatDate(13),
    startTime: "20:00",
    endTime: "23:00",
    budget: 460,
    status: "Pending",
    createdAt: new Date().toISOString(),
  },
  {
    id: "b-15",
    slotId: "s-32",
    venueId: "v-4",
    performerId: "p-3",
    date: formatDate(17),
    startTime: "18:00",
    endTime: "21:00",
    budget: 480,
    status: "Confirmed",
    createdAt: new Date(
      today.getTime() - 2 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },

  // Past confirmed bookings (for review eligibility and history)
  {
    id: "b-past-1",
    slotId: "s-past-1",
    venueId: "v-1",
    performerId: "p-3",
    date: formatDate(-5),
    startTime: "19:00",
    endTime: "21:00",
    budget: 300,
    status: "Confirmed",
    createdAt: new Date(
      today.getTime() - 7 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },
  {
    id: "b-past-2",
    slotId: "s-past-2",
    venueId: "v-3",
    performerId: "p-2",
    date: formatDate(-3),
    startTime: "20:00",
    endTime: "23:00",
    budget: 400,
    status: "Confirmed",
    createdAt: new Date(
      today.getTime() - 4 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },
  {
    id: "b-past-3",
    slotId: "s-past-3",
    venueId: "v-2",
    performerId: "p-2",
    date: formatDate(-10),
    startTime: "22:00",
    endTime: "01:00",
    budget: 480,
    status: "Confirmed",
    createdAt: new Date(
      today.getTime() - 12 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },
  {
    id: "b-past-4",
    slotId: "s-past-4",
    venueId: "v-4",
    performerId: "p-1",
    date: formatDate(-7),
    startTime: "19:00",
    endTime: "22:00",
    budget: 420,
    status: "Confirmed",
    createdAt: new Date(
      today.getTime() - 9 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },
  {
    id: "b-past-5",
    slotId: "s-past-5",
    venueId: "v-1",
    performerId: "p-1",
    date: formatDate(-14),
    startTime: "18:00",
    endTime: "21:00",
    budget: 160,
    status: "Confirmed",
    createdAt: new Date(
      today.getTime() - 16 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },
  {
    id: "b-past-6",
    slotId: "s-past-6",
    venueId: "v-3",
    performerId: "p-3",
    date: formatDate(-8),
    startTime: "19:00",
    endTime: "22:00",
    budget: 290,
    status: "Confirmed",
    createdAt: new Date(
      today.getTime() - 10 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },
  {
    id: "b-past-7",
    slotId: "s-past-7",
    venueId: "v-5",
    performerId: "p-2",
    date: formatDate(-20),
    startTime: "19:00",
    endTime: "22:00",
    budget: 950,
    status: "Confirmed",
    createdAt: new Date(
      today.getTime() - 22 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },
  {
    id: "b-rej-1",
    slotId: "s-rej-1",
    venueId: "v-4",
    performerId: "p-3",
    date: formatDate(-2),
    startTime: "20:00",
    endTime: "23:00",
    budget: 350,
    status: "Rejected",
    createdAt: new Date(
      today.getTime() - 5 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },
];

// ── Messages — 26 messages across 5 rich conversation threads ─────────
export const messages: Message[] = [
  // DJ Electro ↔ Alice (Downtown Club)
  {
    id: "msg-1",
    senderId: "u-perf-2",
    receiverId: "u-mgr-2",
    content:
      "Hi Alice! Regarding the gig at Downtown Club on Friday — is the Pioneer controller standard CDJ-3000?",
    timestamp: new Date(today.getTime() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-2",
    senderId: "u-mgr-2",
    receiverId: "u-perf-2",
    content:
      "Yes! We have 2x CDJ-3000s and a DJM-900NXS2 mixer. Let us know if you need anything else.",
    timestamp: new Date(today.getTime() - 10 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-3",
    senderId: "u-perf-2",
    receiverId: "u-mgr-2",
    content:
      "Perfect. I'll need the booth monitors angled at 45°, and please keep the fog machine running from 10 PM.",
    timestamp: new Date(today.getTime() - 9 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-4",
    senderId: "u-mgr-2",
    receiverId: "u-perf-2",
    content:
      "Noted! Fog machine will be ready. Doors open at 9 PM, you can start set up from 8:30.",
    timestamp: new Date(today.getTime() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-5",
    senderId: "u-perf-2",
    receiverId: "u-mgr-2",
    content:
      "Also, what's the crowd cap tonight? I want to calibrate the volume levels.",
    timestamp: new Date(today.getTime() - 7 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-6",
    senderId: "u-mgr-2",
    receiverId: "u-perf-2",
    content:
      "We're expecting 180 people — near full capacity. We'll have security managing the floor.",
    timestamp: new Date(today.getTime() - 6 * 60 * 60 * 1000).toISOString(),
  },

  // Acoustic Duo ↔ David (Redwood Tavern)
  {
    id: "msg-7",
    senderId: "u-perf-1",
    receiverId: "u-mgr-3",
    content:
      "Hi David, is there a vocal mic provided at Redwood Tavern or should we bring our own?",
    timestamp: new Date(today.getTime() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-8",
    senderId: "u-mgr-3",
    receiverId: "u-perf-1",
    content:
      "Hi Sarah, we provide 3x Shure SM58 vocal mics and stands. You only need to bring your instruments.",
    timestamp: new Date(today.getTime() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-9",
    senderId: "u-perf-1",
    receiverId: "u-mgr-3",
    content:
      "Wonderful! We'll have an acoustic guitar and a small keyboard. Do you have a DI box for the keyboard?",
    timestamp: new Date(today.getTime() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-10",
    senderId: "u-mgr-3",
    receiverId: "u-perf-1",
    content:
      "Yes, we have a Radial J48 DI box available. Parking is free behind the tavern — use the back entrance.",
    timestamp: new Date(today.getTime() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-11",
    senderId: "u-perf-1",
    receiverId: "u-mgr-3",
    content:
      "That's really helpful, thank you! We'll arrive around 6 PM for soundcheck.",
    timestamp: new Date(today.getTime() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-12",
    senderId: "u-mgr-3",
    receiverId: "u-perf-1",
    content:
      "Perfect. Our sound engineer Jake will be there to assist. See you then!",
    timestamp: new Date(today.getTime() - 2 * 60 * 60 * 1000).toISOString(),
  },

  // Mike the Comedian ↔ John (Sector 17 Cafe)
  {
    id: "msg-13",
    senderId: "u-perf-3",
    receiverId: "u-mgr-1",
    content:
      "Hey John! Is there a projector or backdrop at Sector 17 for a comedy night setup?",
    timestamp: new Date(today.getTime() - 30 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-14",
    senderId: "u-mgr-1",
    receiverId: "u-perf-3",
    content:
      "Hi Mike! We have a simple wooden stage and a spotlight. Very intimate — works great for stand-up.",
    timestamp: new Date(today.getTime() - 28 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-15",
    senderId: "u-perf-3",
    receiverId: "u-mgr-1",
    content:
      "Intimate is perfect for observational comedy. Is there a bar tab for performers?",
    timestamp: new Date(today.getTime() - 26 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-16",
    senderId: "u-mgr-1",
    receiverId: "u-perf-3",
    content:
      "Absolutely! Performers get 2 complimentary craft beers or mocktails. Just tell the bartender your name.",
    timestamp: new Date(today.getTime() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-17",
    senderId: "u-perf-3",
    receiverId: "u-mgr-1",
    content:
      "Sold! I'll be there at 6:30 for a quick run-through. Looking forward to it.",
    timestamp: new Date(today.getTime() - 22 * 60 * 60 * 1000).toISOString(),
  },

  // DJ Electro ↔ Emma (Skyline Rooftop)
  {
    id: "msg-18",
    senderId: "u-perf-2",
    receiverId: "u-mgr-4",
    content:
      "Hi Emma, excited about the Skyline Rooftop set! What's the power supply situation on the DJ booth?",
    timestamp: new Date(today.getTime() - 50 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-19",
    senderId: "u-mgr-4",
    receiverId: "u-perf-2",
    content:
      "Hi! We have 4x 16A outlets on the booth and a dedicated power conditioner. More than enough.",
    timestamp: new Date(today.getTime() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-20",
    senderId: "u-perf-2",
    receiverId: "u-mgr-4",
    content: "Brilliant. What time does the venue close?",
    timestamp: new Date(today.getTime() - 46 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-21",
    senderId: "u-mgr-4",
    receiverId: "u-perf-2",
    content:
      "Last call is at 11 PM and we close at midnight. City noise ordinances — strict sound limits after 10.",
    timestamp: new Date(today.getTime() - 44 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-22",
    senderId: "u-perf-2",
    receiverId: "u-mgr-4",
    content:
      "Understood. I'll keep the later part of the set at ambient levels. Looking forward to the sunset backdrop!",
    timestamp: new Date(today.getTime() - 42 * 60 * 60 * 1000).toISOString(),
  },

  // Acoustic Duo ↔ Alice (Downtown Club — scoping acoustic nights)
  {
    id: "msg-23",
    senderId: "u-perf-1",
    receiverId: "u-mgr-2",
    content:
      "Hi Alice, are acoustic performances welcome at the Downtown Club?",
    timestamp: new Date(today.getTime() - 20 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-24",
    senderId: "u-mgr-2",
    receiverId: "u-perf-1",
    content:
      "We do acoustic nights on Tuesdays and Wednesdays! Our crowd loves a good live acoustic set.",
    timestamp: new Date(today.getTime() - 18 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-25",
    senderId: "u-perf-1",
    receiverId: "u-mgr-2",
    content:
      "We do folk-pop covers mostly. Would that fit your Wednesday slot?",
    timestamp: new Date(today.getTime() - 16 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-26",
    senderId: "u-mgr-2",
    receiverId: "u-perf-1",
    content:
      "Absolutely! I'll add you to the shortlist for our next mid-week opening.",
    timestamp: new Date(today.getTime() - 14 * 60 * 60 * 1000).toISOString(),
  },
];

// ── Notifications — 25 entries for all 5 key user accounts ───────────
export const notifications: Notification[] = [
  // ABC Owner (u-org-1)
  {
    id: "n-1",
    userId: "u-org-1",
    title: "Booking Request Received",
    message:
      "Acoustic Duo has requested to perform at Sector 17 Brew & Cafe on " +
      formatDate(5) +
      ".",
    read: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "n-6",
    userId: "u-org-1",
    title: "New Booking Request",
    message:
      "DJ Electro has requested to perform at Sector 17 Cafe on " +
      formatDate(16) +
      ". Review and approve.",
    read: false,
    createdAt: new Date(today.getTime() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "n-7",
    userId: "u-org-1",
    title: "Booking Confirmed",
    message:
      "Mike the Comedian is confirmed for Sector 17 on " +
      formatDate(14) +
      ". Arrival at 6:30 PM.",
    read: true,
    createdAt: new Date(today.getTime() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "n-8",
    userId: "u-org-1",
    title: "Review Received",
    message:
      "Mike the Comedian left a 4-star review for Sector 17 Brew & Cafe. Check your reviews tab.",
    read: true,
    createdAt: new Date(
      today.getTime() - 4 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },
  {
    id: "n-9",
    userId: "u-org-1",
    title: "New Request at Banquet Hall",
    message:
      "Mike the Comedian has requested the Metropolitan Banquet Hall on " +
      formatDate(28) +
      " for ₹1,100.",
    read: false,
    createdAt: new Date(today.getTime() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: "n-10",
    userId: "u-org-1",
    title: "Booking Confirmed at Hall",
    message:
      "Acoustic Duo confirmed for the Metropolitan Banquet Hall on " +
      formatDate(14) +
      ". Budget: ₹1,200.",
    read: false,
    createdAt: new Date(
      today.getTime() - 3 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },

  // XYZ Owner (u-org-2)
  {
    id: "n-3",
    userId: "u-org-2",
    title: "Booking Request Received",
    message:
      "Mike the Comedian has requested to perform at Redwood Tavern & Grill on " +
      formatDate(3) +
      ".",
    read: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "n-11",
    userId: "u-org-2",
    title: "Review Received",
    message:
      "DJ Electro left you a 5-star review for Redwood Tavern! View the full feedback in your reviews.",
    read: false,
    createdAt: new Date(
      today.getTime() - 2 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },
  {
    id: "n-12",
    userId: "u-org-2",
    title: "Booking Confirmed",
    message:
      "DJ Electro confirmed for Redwood Tavern on " +
      formatDate(10) +
      ". Payout: ₹310.",
    read: true,
    createdAt: new Date(today.getTime() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "n-13",
    userId: "u-org-2",
    title: "New Slot Request at Skyline",
    message:
      "Acoustic Duo has requested the Skyline Rooftop slot on " +
      formatDate(13) +
      ". Please review.",
    read: false,
    createdAt: new Date(today.getTime() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "n-14",
    userId: "u-org-2",
    title: "Booking Rejected",
    message:
      "Skyline Rooftop rejected Mike the Comedian's request for " +
      formatDate(-2) +
      ".",
    read: true,
    createdAt: new Date(
      today.getTime() - 5 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },

  // DJ Electro (u-perf-2)
  {
    id: "n-2",
    userId: "u-perf-2",
    title: "Booking Confirmed",
    message:
      "Your performance at The Downtown Club & Lounge on " +
      formatDate(6) +
      " is confirmed!",
    read: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "n-15",
    userId: "u-perf-2",
    title: "New Gig Confirmed",
    message:
      "Redwood Tavern confirmed your slot on " +
      formatDate(10) +
      ". Payout: ₹310.",
    read: false,
    createdAt: new Date(today.getTime() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "n-16",
    userId: "u-perf-2",
    title: "Review Received",
    message:
      "Redwood Tavern left you a 5-star review. Your overall rating has improved!",
    read: false,
    createdAt: new Date(
      today.getTime() - 2 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },
  {
    id: "n-17",
    userId: "u-perf-2",
    title: "Booking Confirmed",
    message:
      "Your set at Downtown Club on " +
      formatDate(12) +
      " is locked in. Payout: ₹480.",
    read: true,
    createdAt: new Date(
      today.getTime() - 2 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },

  // Acoustic Duo (u-perf-1)
  {
    id: "n-18",
    userId: "u-perf-1",
    title: "Gig Confirmed at Redwood",
    message:
      "Your booking at Redwood Tavern on " +
      formatDate(5) +
      " is confirmed. Payout: ₹300.",
    read: true,
    createdAt: new Date(today.getTime() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "n-19",
    userId: "u-perf-1",
    title: "Request Under Review",
    message:
      "Your request for Skyline Rooftop on " +
      formatDate(13) +
      " is under review by Emma.",
    read: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "n-20",
    userId: "u-perf-1",
    title: "Review Received",
    message:
      "Skyline Rooftop left a 4-star review for your last performance. Great feedback!",
    read: false,
    createdAt: new Date(
      today.getTime() - 7 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },
  {
    id: "n-21",
    userId: "u-perf-1",
    title: "Gig Confirmed at Hall",
    message:
      "Metropolitan Banquet Hall confirmed your slot on " +
      formatDate(14) +
      ". Payout: ₹1,200!",
    read: false,
    createdAt: new Date(
      today.getTime() - 3 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },

  // Mike the Comedian (u-perf-3)
  {
    id: "n-22",
    userId: "u-perf-3",
    title: "Booking Confirmed",
    message:
      "Mike, your comedy night at Sector 17 on " +
      formatDate(14) +
      " is confirmed! Payout: ₹175.",
    read: true,
    createdAt: new Date(today.getTime() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "n-23",
    userId: "u-perf-3",
    title: "Gig Request Pending",
    message:
      "Your request for Metropolitan Banquet Hall on " +
      formatDate(28) +
      " is awaiting approval.",
    read: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "n-24",
    userId: "u-perf-3",
    title: "Booking Rejected at Skyline",
    message:
      "Skyline Rooftop declined your request for " +
      formatDate(-2) +
      ". Consider applying to another slot.",
    read: false,
    createdAt: new Date(
      today.getTime() - 5 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },
  {
    id: "n-25",
    userId: "u-perf-3",
    title: "Review Received",
    message:
      "ABC Hospitality gave you a 5-star review for your Sector 17 comedy show!",
    read: true,
    createdAt: new Date(
      today.getTime() - 4 * 24 * 60 * 60 * 1000,
    ).toISOString(),
  },
  {
    id: "n-26",
    userId: "u-perf-3",
    title: "Booking Confirmed at Redwood",
    message:
      "Redwood Tavern confirmed your open-mic set on " +
      formatDate(3) +
      ". Payout: ₹320.",
    read: false,
    createdAt: new Date(today.getTime() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "n-27",
    userId: "u-perf-3",
    title: "Upcoming Gig Reminder",
    message:
      "Reminder: your confirmed set at Skyline Rooftop is on " +
      formatDate(17) +
      ". Payout: ₹480.",
    read: false,
    createdAt: new Date(today.getTime() - 6 * 60 * 60 * 1000).toISOString(),
  },
];

// ── Reviews — 14 cross-posted reviews for all past bookings ───────────
export const reviews: Review[] = [
  // ABC reviews
  {
    id: "r-1",
    bookingId: "b-past-1",
    reviewerId: "u-org-1",
    revieweeId: "u-perf-3",
    rating: 5,
    comment:
      "Mike was absolutely hilarious! The crowd loved the observational humor and he kept the energy clean and professional. Highly recommend.",
    createdAt: formatDate(-4),
  },
  {
    id: "r-2",
    bookingId: "b-past-1",
    reviewerId: "u-perf-3",
    revieweeId: "u-org-1",
    rating: 4,
    comment:
      "Great cozy cafe to perform at. Helpful staff, though the stage lighting was a bit dim. Will definitely play here again.",
    createdAt: formatDate(-4),
  },
  {
    id: "r-7",
    bookingId: "b-past-3",
    reviewerId: "u-org-1",
    revieweeId: "u-perf-2",
    rating: 5,
    comment:
      "DJ Electro absolutely packed the Downtown Club. Flawless mix, the crowd was electric until closing. Will rebook immediately.",
    createdAt: formatDate(-9),
  },
  {
    id: "r-8",
    bookingId: "b-past-3",
    reviewerId: "u-perf-2",
    revieweeId: "u-org-1",
    rating: 5,
    comment:
      "The Downtown Club is a DJ's dream. The sound system is world-class and the staff were totally on point. Incredible venue.",
    createdAt: formatDate(-9),
  },
  {
    id: "r-9",
    bookingId: "b-past-5",
    reviewerId: "u-org-1",
    revieweeId: "u-perf-1",
    rating: 4,
    comment:
      "Sarah & Jack delivered a lovely acoustic evening at Sector 17. Guests were captivated the whole time. A real treat.",
    createdAt: formatDate(-13),
  },
  {
    id: "r-10",
    bookingId: "b-past-5",
    reviewerId: "u-perf-1",
    revieweeId: "u-org-1",
    rating: 5,
    comment:
      "Sector 17 Brew & Cafe is the perfect acoustic venue. Warm crowd, great sound monitor, and the staff were so welcoming!",
    createdAt: formatDate(-13),
  },
  {
    id: "r-13",
    bookingId: "b-past-7",
    reviewerId: "u-org-1",
    revieweeId: "u-perf-2",
    rating: 5,
    comment:
      "DJ Electro's banquet hall set was transcendent. 600 guests dancing — absolutely phenomenal energy all evening.",
    createdAt: formatDate(-19),
  },
  {
    id: "r-14",
    bookingId: "b-past-7",
    reviewerId: "u-perf-2",
    revieweeId: "u-org-1",
    rating: 5,
    comment:
      "The Metropolitan Banquet Hall is a bucket-list venue. Grand stage, crystal-clear line array, and a totally professional team. 10/10.",
    createdAt: formatDate(-19),
  },

  // XYZ reviews
  {
    id: "r-3",
    bookingId: "b-past-2",
    reviewerId: "u-org-2",
    revieweeId: "u-perf-2",
    rating: 5,
    comment:
      "Excellent techno set by DJ Electro! Had the tavern dancing all night. Very professional setup.",
    createdAt: formatDate(-2),
  },
  {
    id: "r-4",
    bookingId: "b-past-2",
    reviewerId: "u-perf-2",
    revieweeId: "u-org-2",
    rating: 4,
    comment:
      "Redwood Tavern has a great vibe — rustic, warm, and the crowd really gets into live music. The DI box was a bit dated but worked fine.",
    createdAt: formatDate(-2),
  },
  {
    id: "r-5",
    bookingId: "b-past-4",
    reviewerId: "u-org-2",
    revieweeId: "u-perf-1",
    rating: 4,
    comment:
      "Acoustic Duo played a beautiful jazz-folk set at Skyline. Perfect for our rooftop crowd. Very polished and professional.",
    createdAt: formatDate(-6),
  },
  {
    id: "r-6",
    bookingId: "b-past-4",
    reviewerId: "u-perf-1",
    revieweeId: "u-org-2",
    rating: 5,
    comment:
      "Skyline Rooftop is breathtaking. Performing at sunset with the city below us was unforgettable. Excellent equipment and management.",
    createdAt: formatDate(-6),
  },
  {
    id: "r-11",
    bookingId: "b-past-6",
    reviewerId: "u-org-2",
    revieweeId: "u-perf-3",
    rating: 3,
    comment:
      "Mike's set was entertaining but ran 15 minutes over time. Crowd liked the material but pacing could improve for a tavern setting.",
    createdAt: formatDate(-7),
  },
  {
    id: "r-12",
    bookingId: "b-past-6",
    reviewerId: "u-perf-3",
    revieweeId: "u-org-2",
    rating: 4,
    comment:
      "Redwood Tavern is a gem for stand-up — intimate and packed. The owner was friendly and the staff set up the mic really well.",
    createdAt: formatDate(-7),
  },
];
